#!/bin/sh

version_name="$1"

shift

message="$@"

gradle_script=app/build.gradle.kts

if [ -z "$version_name" ] && [ -z "$message" ]
then
	echo 'Usage: version <Name> <Message>'

	exit 1
fi

if ! git tag -a "$version_name" -m "$message"
then
	echo "Cannot create tag $version_name"

	exit 1
fi

echo "Created new Git tag: $version_name"

if ! [ -f "$gradle_script" ]
then
	echo "Cannot find $gradle_script"

	exit 1
fi

if ! version_code=$(git tag | wc -l)
then
	echo 'Cannot get version code'

	exit 1
fi

echo "Version code: $version_code"

sed -i "s/versionCode = .*/versionCode = $version_code/" "$gradle_script"
sed -i "s/versionName = .*/versionName = \"$version_name\"/" "$gradle_script"
